# Generated by Django 4.0.2 on 2022-08-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldAreaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec', models.FloatField(null=True)),
                ('nh4n', models.FloatField(null=True)),
                ('no3n', models.FloatField(null=True)),
                ('total_nitrogen', models.FloatField(null=True)),
                ('nh4_per_nitrogen', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('cao', models.FloatField(null=True)),
                ('mgo', models.FloatField(null=True)),
                ('k2o', models.FloatField(null=True)),
                ('base_saturation', models.FloatField(null=True)),
                ('cao_per_mgo', models.FloatField(null=True)),
                ('mgo_per_k2o', models.FloatField(null=True)),
                ('phosphorus_absorption', models.FloatField(null=True)),
                ('p2o5', models.FloatField(null=True)),
                ('cec', models.FloatField(null=True)),
                ('humus', models.FloatField(null=True)),
                ('bulk_density', models.FloatField(null=True)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldAreaSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prefecture', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('latlon', models.CharField(max_length=256, null=True)),
                ('class_clops', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('year', 'name'), name='year_name_unique'),
        ),
        migrations.AddField(
            model_name='fields',
            name='clops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.clops'),
        ),
        migrations.AddField(
            model_name='fields',
            name='companies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.companies'),
        ),
        migrations.AddField(
            model_name='fieldareasummary',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.fields'),
        ),
        migrations.AddField(
            model_name='fieldareasummary',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.period'),
        ),
        migrations.AddField(
            model_name='fieldareadetail',
            name='field_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.fieldarea'),
        ),
        migrations.AddField(
            model_name='fieldareadetail',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.period'),
        ),
        migrations.AddField(
            model_name='fieldarea',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.fields'),
        ),
        migrations.AddConstraint(
            model_name='fieldareasummary',
            constraint=models.UniqueConstraint(fields=('period', 'fields'), name='period_fields_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldareadetail',
            constraint=models.UniqueConstraint(fields=('period', 'field_area'), name='period_field_area_unique'),
        ),
        migrations.AddConstraint(
            model_name='fieldarea',
            constraint=models.UniqueConstraint(fields=('fields', 'name'), name='fields_name_unique'),
        ),
    ]
