# Generated by Django 4.0.2 on 2022-08-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prefecture', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('latlon', models.CharField(max_length=256, null=True)),
                ('cultivation_method', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('clops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.clops')),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.companies')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAreaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec', models.IntegerField(null=True)),
                ('nh4n', models.IntegerField(null=True)),
                ('no3n', models.IntegerField(null=True)),
                ('inorganic_nitrogen', models.IntegerField(null=True)),
                ('nh4', models.IntegerField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('cao', models.IntegerField(null=True)),
                ('mgo', models.IntegerField(null=True)),
                ('k2o', models.IntegerField(null=True)),
                ('base_saturation', models.FloatField(null=True)),
                ('cao_per_mgo', models.FloatField(null=True)),
                ('mgo_per_k2o', models.FloatField(null=True)),
                ('phosphorus_absorption', models.IntegerField(null=True)),
                ('p2o5', models.IntegerField(null=True)),
                ('cec', models.IntegerField(null=True)),
                ('humus', models.FloatField(null=True)),
                ('bulk_density', models.FloatField(null=True)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_report.fields')),
            ],
        ),
    ]
