# Generated by Django 4.0.2 on 2023-05-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CultivationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('prefecture', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('latlon', models.CharField(max_length=256, null=True)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec', models.FloatField(null=True)),
                ('nh4n', models.FloatField(null=True)),
                ('no3n', models.FloatField(null=True)),
                ('total_nitrogen', models.FloatField(null=True)),
                ('nh4_per_nitrogen', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('cao', models.FloatField(null=True)),
                ('mgo', models.FloatField(null=True)),
                ('k2o', models.FloatField(null=True)),
                ('base_saturation', models.FloatField(null=True)),
                ('cao_per_mgo', models.FloatField(null=True)),
                ('mgo_per_k2o', models.FloatField(null=True)),
                ('phosphorus_absorption', models.FloatField(null=True)),
                ('p2o5', models.FloatField(null=True)),
                ('cec', models.FloatField(null=True)),
                ('humus', models.FloatField(null=True)),
                ('bulk_density', models.FloatField(null=True)),
                ('remark', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('year', 'name'), name='year_name_unique'),
        ),
        migrations.AddField(
            model_name='landscore',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.area'),
        ),
        migrations.AddField(
            model_name='landscore',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crop'),
        ),
        migrations.AddField(
            model_name='landscore',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.land'),
        ),
        migrations.AddField(
            model_name='landscore',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.period'),
        ),
        migrations.AddField(
            model_name='landreview',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.land'),
        ),
        migrations.AddField(
            model_name='landreview',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.period'),
        ),
        migrations.AddField(
            model_name='land',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AddField(
            model_name='land',
            name='cultivation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cultivationtype'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('name',), name='name_unique'),
        ),
        migrations.AddConstraint(
            model_name='landscore',
            constraint=models.UniqueConstraint(fields=('land', 'area', 'period'), name='land_area_period_unique'),
        ),
        migrations.AddConstraint(
            model_name='landreview',
            constraint=models.UniqueConstraint(fields=('land', 'period'), name='land_period_unique'),
        ),
    ]
